### ISSUE TITLE
New Site: https://www.receitasnestle.com.br/

### ISSUE THREAD

**Issue by fboaventura** [hhursev/recipe-scrapers#108]
Site: https://www.receitasnestle.com.br/
Recipe: https://www.receitasnestle.com.br/receitas/strogonoff

**Comment by hotfix** [comment]
i was trying to do it, but got the following error

```
ERROR: test_host (test_receitasnestle.TestReceitasnestleScraper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Programme\Python\lib\site-packages\extruct\jsonld.py", line 34, in _extract_items
    data = json.loads(script, strict=False)
  File "D:\Programme\Python\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "D:\Programme\Python\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 19 column 2 (char 383)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\projekte\recipe-scrapers\tests\__init__.py", line 13, in setUp
    self.harvester_class = self.scraper_class(testfile, test=True, **options)
  File "d:\projekte\recipe-scrapers\recipe_scrapers\_abstract.py", line 27, in __init__
    self.schema = SchemaOrg(page_data, host=self.host())
  File "d:\projekte\recipe-scrapers\recipe_scrapers\_schemaorg.py", line 25, in __init__
    uniform=True,
  File "D:\Programme\Python\lib\site-packages\extruct\_extruct.py", line 101, in extract
    output[syntax] = list(extract(document, base_url=base_url))
  File "D:\Programme\Python\lib\site-packages\extruct\jsonld.py", line 26, in extract_items
    for items in map(self._extract_items, self._xp_jsonld(document))
  File "D:\Programme\Python\lib\site-packages\extruct\jsonld.py", line 25, in <listcomp>
    item
  File "D:\Programme\Python\lib\site-packages\extruct\jsonld.py", line 38, in _extract_items
    HTML_OR_JS_COMMENTLINE.sub('', script), strict=False)
  File "D:\Programme\Python\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "D:\Programme\Python\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 19 column 2 (char 383)
```
