### ISSUE TITLE
New Site: https://www.saboresajinomoto.com.br/

### ISSUE THREAD

**Issue by fboaventura** [hhursev/recipe-scrapers#111]
Site: https://www.saboresajinomoto.com.br/
Recipe: https://www.saboresajinomoto.com.br/receita/pure-de-batata-com-frango

**Comment by PatrickPierce** [comment]
I started to work on this, but I think extruct fails to parse the data when grabbing the URL.

```

>>> scraper = scrape_me('https://www.saboresajinomoto.com.br/receita/pure-de-batata-com-frango')
Traceback (most recent call last):
  File "/home/patrick/Projects/git_repo/recipe-scrapers/.venv/lib64/python3.8/site-packages/extruct/jsonld.py", line 34, in _extract_items
    data = json.loads(script, strict=False)
  File "/usr/lib64/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 30 column 2 (char 2051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/Projects/git_repo/recipe-scrapers/recipe_scrapers/__init__.py", line 183, in scrape_me
    return scraper(url_path, **options)
  File "/home/patrick/Projects/git_repo/recipe-scrapers/recipe_scrapers/_abstract.py", line 106, in __init__
    self.schema = SchemaOrg(page_data)
  File "/home/patrick/Projects/git_repo/recipe-scrapers/recipe_scrapers/_schemaorg.py", line 21, in __init__
    data = extruct.extract(
  File "/home/patrick/Projects/git_repo/recipe-scrapers/.venv/lib64/python3.8/site-packages/extruct/_extruct.py", line 101, in extract
    output[syntax] = list(extract(document, base_url=base_url))
  File "/home/patrick/Projects/git_repo/recipe-scrapers/.venv/lib64/python3.8/site-packages/extruct/jsonld.py", line 24, in extract_items
    return [
  File "/home/patrick/Projects/git_repo/recipe-scrapers/.venv/lib64/python3.8/site-packages/extruct/jsonld.py", line 24, in <listcomp>
    return [
  File "/home/patrick/Projects/git_repo/recipe-scrapers/.venv/lib64/python3.8/site-packages/extruct/jsonld.py", line 37, in _extract_items
    data = json.loads(
  File "/usr/lib64/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 30 column 2 (char 2051)
```
