### ISSUE TITLE
scraper not getting food network info

### ISSUE THREAD

**Issue by AnnieSixgun** [hhursev/recipe-scrapers#1119]
**The URL of the recipe(s) that are not being scraped correctly**

[- https:// ...](https://www.foodnetwork.com/recipes/ina-garten/asian-grilled-salmon-recipe-1944413)

...

the recipe info

...

Looks Like We Couldn't Find Anything 

...

**Comment by jknndy** [comment]
@AnnieSixgun , I could not replicate the issue here. Could you double check that you're using the latest version of the library?

```python
>>> from recipe_scrapers import scrape_me
>>> scraper = scrape_me('https://www.foodnetwork.com/recipes/ina-garten/asian-grilled-salmon-recipe-1944413')
>>> scraper.to_json()
{'author': 'Ina Garten Bio & Top Recipes', 'canonical_url': 'https://www.foodnetwork.com/recipes/ina-garten/asian-grilled-salmon-recipe-1944413', 'category': 'main-dish', 'cook_time': 9, 'cuisine': 'asian', 'description': "Ina Garten's Asian Grilled Salmon, from Barefoot Contessa on Food Network, is a light, quick main dish with salty-sharp flavors like Dijon and soy sauce.", .... }
>>> 
```

**Comment by mlduff** [comment]
@AnnieSixgun I also couldn't replicate the issue, although I did notice that `prep_time` and `cook_time` have not been implemented despite them being available in the schema - @jknndy did you want me to make this improvement?

**Comment by jknndy** [comment]
> @AnnieSixgun I also couldn't replicate the issue, although I did notice that `prep_time` and `cook_time` have not been implemented despite them being available in the schema - @jknndy did you want me to make this improvement?

Up to you @mlduff ! I've been exploring this issue on a larger scale to see if we can populate all possible coverage that is available so it'll get caught in that regardless

**Comment by thewolfman56** [comment]
I am having this issue as well using v.15.0.0


    >>> from recipe_scrapers import scrape_html
    >>> url = "https://www.foodnetwork.com/recipes/melissa-darabian/pork-carnitas-recipe-1925103"
    >>> name = input('What is your name, burger seeker?\n')
    What is your name, burger seeker?
    Me
    >>> html = requests.get(url, headers={"User-Agent": f"Burger Seeker {name}"}).content
    >>> scraper = scrape_html(html, org_url=url)
    >>> scraper.title()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\steph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\exception_handling.py", line 63, in decorated_method_wrapper
        return decorated(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\steph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\html_tags_stripper.py", line 74, in decorated_method_wrapper
        decorated_func_result = decorated(self, *args, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\steph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\normalize_string.py", line 33, in decorated_method_wrapper
        return normalize_string(decorated(self, *args, **kwargs))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\steph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\schemaorg_fill.py", line 66, in decorated_method_wrapper
        raise e
      File "C:\Users\steph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\schemaorg_fill.py", line 57, in decorated_method_wrapper
        return decorated(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\steph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\_abstract.py", line 94, in title
        raise NotImplementedError("This should be implemented.")
    NotImplementedError: This should be implemented.

**Comment by goandgit** [comment]
Using 15.1 and Python 3.10.13.

I'm not having issues with foodnetwork.com. However I am having trouble with foodnetwork.co.uk.

```
>>> from recipe_scrapers import scrape_html
>>> url = "https://foodnetwork.co.uk/recipes/paneer-fish-cakes-apple-and-fig-chutney"
>>> html = requests.get(url).content
>>> scraper = scrape_html(html, org_url=url, wild_mode=True)
>>> scraper.title()
'Paneer Fishcakes with Chutney'
>>> scraper.instructions()
''
>>> 
```
The instructions call does not throw an exception just return a blank value. `instructions_list` is also an empty list.

**Comment by goandgit** [comment]
Since the schema is missing the instructions for the uk site I thought I'd try to add it and submit a PR however I'm having some trouble. Beautiful Soup is not finding any elements that I'm trying to get. So out of curiousity I exported the html to a file and most of the site page is missing. Here's the code:

```
def instructions(self):
    if self.host() =="foodnetwork.co.uk":
        with open("output1.html", "w") as file:
            file.write(str(self.soup))
        div = self.soup.select(".legacy-method content e-instructions")
    return div
```

This returns an empty list. 

[output1.zip](https://github.com/user-attachments/files/17090375/output1.zip)

I attached the output file since it was too large to post here. You'll see that it's just one huge div, missing most of the content of the site.

**Comment by goandgit** [comment]
Sorry for all the comments but after posting my comment above I realized I answered my own question. I'll fix my request and then hopefully get the instructions implemented right after.

**Comment by goandgit** [comment]
So the issue was the source for the page existed in a data attribute in a div as JSON. Interestingly, the schema is also duplicated once in the head and once in the body with only the body updating after the initial page load. This means there are conflicting schemas on the page.

I think it would be helpful to not restrict the schema search to the head and to instead check the whole document and use the last one found. Foodnetwork.com has also moved the schema to the body. @jayaddison, what do you think?

**Comment by jayaddison** [comment]
Hi @goandgit - thanks for digging into this, and I'm sorry for taking so long to reply.  To check whether I'm up-to-date on the details: it seem like one top-level domain applies some kind of bot-filtering applied, and the other does not?

Re: where to retrieve metadata from: the logic regarding `schema.org` extraction is mostly delegated to [`extruct`](https://github.com/scrapinghub/extruct/); I'd need to do some more investigation to figure out exactly why particular content might not be retrieved from one area or another of a recipe page.

**Comment by goandgit** [comment]
> Hi @goandgit - thanks for digging into this, and I'm sorry for taking so long to reply. 

No need for apologies.

> To check whether I'm up-to-date on the details: it seem like one top-level domain applies some kind of bot-filtering applied, and the other does not?

That seems to be the case. Yes. The uk site had, at last review, incomplete schema info in the head. The actual data is in some JSON in a div. Not sure if that makes it outside of the scope of this project as it can be handled separately. 

The .com site is blocking. (last I checked)

> Re: where to retrieve metadata from: the logic regarding `schema.org` extraction is mostly delegated to [`extruct`](https://github.com/scrapinghub/extruct/); I'd need to do some more investigation to figure out exactly why particular content might not be retrieved from one area or another of a recipe page.

I was going to dig here a bit as well but Food Network is doing some weird things that they probably have reason for, that makes scraping problematic.
