### ISSUE TITLE
Kitchn scraping not working

### ISSUE THREAD

**Issue by calm108** [hhursev/recipe-scrapers#1148]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.thekitchn.com/herby-tahini-buttermilk-ranch-recipe-23185190
- https://www.thekitchn.com/french-onion-meatballs-recipe-23585839
...

**The results you expect to see**

... teh recipe pulled into Mealie

**The results (including any Python error messages) that you are seeing**

... 2024-06-04 20:44:09 INFO     2024-06-04T20:44:09 - HTTP Request: GET https://www.thekitchn.com/french-onion-meatballs-recipe-23585839 "HTTP/1.1 403 Forbidden"
2024-06-04 20:44:09 INFO     2024-06-04T20:44:09 - HTTP Request: GET https://www.thekitchn.com/french-onion-meatballs-recipe-23585839 "HTTP/1.1 403 Forbidden"
2024-06-04 20:44:09 INFO     2024-06-04T20:44:09 - [172.24.0.1:59336] 400 Bad Request "POST /api/recipes/create-url HTTP/1.1"

**Comment by thewolfman56** [comment]
I'm having this issue as well.  It used to work with thekitchn.com

**Comment by jknndy** [comment]
Thanks for the bug report, unfortunately I am unable to reproduce this issue locally. Could you ensure you're using the latest version of the library & provide any error messages/outputs you're receiving!

```python
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from recipe_scrapers import scrape_me
>>> scraper = scrape_me('https://www.thekitchn.com/herby-tahini-buttermilk-ranch-recipe-23185190#post-recipe-281880337')
>>> scraper.title()
'Herby Tahini Buttermilk Ranch'
>>> scraper.ingredients()
['1 medium lemon', '1/4 cup buttermilk', '1/4 cup tahini, such as Soom or Seed & Mill', '1 teaspoon garlic powder', '1 teaspoon maple syrup', '1/2 teaspoon onion powder', '1/2 teaspoon kosher salt, plus more as needed', 'Freshly ground black pepper', '1 to 2 tablespoons cold water, as needed', '2 tablespoons finely chopped fresh parsley leaves', '1 tablespoon finely chopped fresh chives', '1 tablespoon finely chopped fresh dill fronds']
>>> 
```

**Comment by thewolfman56** [comment]
I received an error while using Mealie that I just updated so that it includes recipe scraper version 15.0.0.

https://www.thekitchn.com/how-to-make-thanksgiving-honey-ham-in-the-slow-cooker-237814

If there is a way to the get the scraper log from Mealie, I would be more than happy to add it.  All I can see in the Mealie log is that access is forbidden

INFO     2024-08-02T18:04:11 - HTTP Request: GET https://www.thekitchn.com/how-to-make-thanksgiving-honey-ham-in-the-slow-cooker-237814 "HTTP/1.1 403 Forbidden

**Comment by thewolfman56** [comment]
I tried using recipe-scraper through Windows powershell and get this error
`>>> from recipe_scrapers import scrape_html
>>> url = "https://www.thekitchn.com/how-to-make-thanksgiving-honey-ham-in-the-slow-cooker-237814"
>>> name = input('What is your name, burger seeker?\n')
What is your name, burger seeker?
Me
>>> html = requests.get(url, headers={"User-Agent": f"Burger Seeker {name}"}).content
>>> scraper = scrape_html(html, org_url=url)
>>> scraper.links()
[{'href': 'https://www.perimeterx.com/whywasiblocked'}]
>>> scraper.ingredients()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\exception_handling.py", line 63, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\html_tags_stripper.py", line 74, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\schemaorg_fill.py", line 66, in decorated_method_wrapper
    raise e
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\plugins\schemaorg_fill.py", line 57, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\recipe_scrapers\_abstract.py", line 98, in ingredients
    raise NotImplementedError("This should be implemented.")
NotImplementedError: This should be implemented.`

When I try the allrecipes example in the readme, I am able to receive information back.  For example,
`>>> scraper.title()
'Spinach and Feta Turkey Burgers'
>>> scraper.ingredients()
['cooking spray', '2 pounds ground turkey', '1 (10 ounce) box frozen chopped spinach, thawed and squeezed dry', '4 ounces feta cheese', '2 large eggs, beaten', '2 cloves garlic, minced']`

**Comment by jayaddison** [comment]
Hi folks - an HTTP 403 response generally indicates that the webserver decided not to allow you to access the webpage that you requested.  When a recipe site issues that response code, they're unlikely to include the recipe HTML in the response, and so Mealie/`recipe-scrapers` won't be able to interpret it.
