### ISSUE TITLE
Kitchenstories scrapper not detected

### ISSUE THREAD

**Issue by hhopke** [hhursev/recipe-scrapers#1261]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

"https://www.kitchenstories.com/de/rezepte/susskartoffel-curry"

**The results you expect to see**

Scrapped recipe

**The results (including any Python error messages) that you are seeing**

`url = "https://www.kitchenstories.com/de/rezepte/susskartoffel-curry"
name = input('What is your name, risotto sampler?\n')
html = requests.get(url, headers={"User-Agent": f"Risotto Sampler {name}"}).content
scraper = scrape_html(html, org_url=url, wild_mode=False)
scraper.host()
scraper.title()
scraper.total_time()
scraper.image()
scraper.ingredients()
scraper.ingredient_groups()
scraper.instructions()
scraper.instructions_list()
scraper.yields()
scraper.to_json()
scraper.links()
scraper.nutrients()  # not always available
scraper.canonical_url()  # not always available
scraper.equipment()  # not always available
scraper.cooking_method()  # not always available
scraper.keywords()  # not always available
scraper.dietary_restrictions() # not always available`

`Traceback (most recent call last):
  File "...\scratches\scratch_7.py", line 11, in <module>
    scraper.title()
  File "~\recipe_scrapers\plugins\exception_handling.py", line 63, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ~\recipe_scrapers\plugins\html_tags_stripper.py", line 74, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\recipe_scrapers\plugins\normalize_string.py", line 33, in decorated_method_wrapper
    return normalize_string(decorated(self, *args, **kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\recipe_scrapers\plugins\schemaorg_fill.py", line 66, in decorated_method_wrapper
    raise e
  File "~\recipe_scrapers\plugins\schemaorg_fill.py", line 57, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\recipe_scrapers\_abstract.py", line 95, in title
    raise NotImplementedError("This should be implemented.")
NotImplementedError: This should be implemented.`

**Comment by jayaddison** [comment]
@hhopke no problem at all, thanks for responding.  I have one idea, although it may be something you've already considered: do you know whether the relevant pages display as expected when opened in a popular web browser?  That could provide one item of information, and perhaps a workaround:

  * Info: it may help confirm whether the problem could somehow be related to the script used to retrieve the recipe page (a difference in user-agent).
  * Workaround: if the page does load correctly in a browser, you should be able to save the source HTML of the page from your browser to a file, and then to update the scripting to read that file and scrape from there instead.

Unfortunately there's often not a lot we can do about transient network errors and network/server filtering -- so I can't guarantee a successful result; but if the page does load in other browsers then, in theory at least, we have more options.
