### ISSUE TITLE
[Americas Test Kitchen] - Scraper broken

### ISSUE THREAD

**Issue by sudobash1** [hhursev/recipe-scrapers#1317]
**Pre-filing checks**

- [ x] I have searched for open issues that report the same problem
- [ x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

Seems like all recipes broken. Here are some examples:

- https://www.americastestkitchen.com/recipes/9967-pasta-with-caramelized-onions-pecorino-romano-and-black-pepper
- https://www.americastestkitchen.com/recipes/16182-braised-chicken-and-mushrooms-over-polenta
- https://www.americastestkitchen.com/recipes/528-classic-creme-brulee

**The results you expect to see**

It used to work (72 hours ago). Now it doesn't find any recipe.

**The results (including any Python error messages) that you are seeing**

Python error:

```
ERROR    2024-10-21T17:05:05 - Exception in ASGI application
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/app/mealie/routes/_base/routers.py", line 35, in custom_route_handler
    response = await original_route_handler(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 203, in parse_recipe_url
    recipe, extras = await create_from_url(req.url, self.translator)
  File "/app/mealie/services/scraper/scraper.py", line 34, in create_from_url
    new_recipe, extras = await scraper.scrape(url)
  File "/app/mealie/services/scraper/recipe_scraper.py", line 43, in scrape
    result = await scraper.parse()
  File "/app/mealie/services/scraper/scraper_strategies.py", line 233, in parse
    scraped_data = await self.scrape_url()
  File "/app/mealie/services/scraper/scraper_strategies.py", line 204, in scrape_url
    scraped_schema = scrape_html(recipe_html, org_url=self.url, supported_only=False)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/recipe_scrapers/__init__.py", line 844, in scrape_html
    return SCRAPERS[host_name](html=html, url=org_url)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/recipe_scrapers/_abstract.py", line 33, in __init__
    for name, _ in inspect.getmembers(self, inspect.ismethod):
  File "/usr/local/lib/python3.10/inspect.py", line 469, in getmembers
    value = getattr(object, key)
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/recipe_scrapers/americastestkitchen.py", line 98, in _get_additional_details
    name = list(j["props"]["initialState"]["content"]["documents"])[0]
IndexError: list index out of range
```

It looks like America's Test Kitchen changed the json on the page.

**Comment by sudobash1** [comment]
I am using this patch in my docker container, and it seems to work like it did before.

``` diff
diff --git a/recipe_scrapers/americastestkitchen.py b/recipe_scrapers/americastestkitchen.py
index 589b9c95..08fdc68f 100644
--- a/recipe_scrapers/americastestkitchen.py
+++ b/recipe_scrapers/americastestkitchen.py
@@ -71,5 +71,4 @@ class AmericasTestKitchen(AbstractScraper):
     @functools.cached_property
     def _get_additional_details(self):
         j = json.loads(self.soup.find(type="application/json").string)
-        name = list(j["props"]["initialState"]["content"]["documents"])[0]
-        return j["props"]["initialState"]["content"]["documents"][name]
+        return j["props"]["pageProps"]["data"]
```

**Comment by smilerz** [comment]
@jayaddison - this has switched a couple of times now and `schema.ingredients()` works again.

I'm not sure if they are transitioning to a new schema for recipes or what's happening.  What do you think about having it check both formats (and maybe the built in `schema.ingredients()` too?) to provide some stability to this particular scraper?

**Comment by jayaddison** [comment]
@smilerz are you able to confirm that stale cache / proxy cache data is not the problem?  If so and their site appears to be intermittently changing between formats, it could be an argument for supporting both (we've got some discussing going about this in #1320, cc @jknndy).

**Comment by smilerz** [comment]
> @smilerz are you able to confirm that stale cache / proxy cache data is not the problem?

I've been able to reproduce the behavior on multiple recipes.

**Comment by jayaddison** [comment]
Ok, thank you.  In that case, I believe we should support both formats in parallel until the site stabilizes on one or the other.
