### ISSUE TITLE
Argiro: failure processing schema.org metadata

### ISSUE THREAD

**Issue by jayaddison** [hhursev/recipe-scrapers#1363]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.argiro.gr/recipe/gemista-tis-argiros/

**The results you expect to see**

Recipe scrape results should be retrieved successfully.

**The results (including any Python error messages) that you are seeing**

```python
>>> from recipe_scrapers import scrape_html
>>> s = scrape_html(html=None, org_url='https://www.argiro.gr/recipe/gemista-tis-argiros/', online=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<filtered>/recipe_scrapers/__init__.py", line 906, in scrape_html
    return SCRAPERS[host_name](html=html, url=org_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<filtered>/recipe_scrapers/_abstract.py", line 29, in __init__
    self.schema = SchemaOrg(self.page_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<filtered>/recipe_scrapers/_schemaorg.py", line 66, in __init__
    if person := self._find_entity(item, "Person"):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<filtered>/recipe_scrapers/_schemaorg.py", line 37, in _find_entity
    if self._contains_schematype(node, schematype):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<filtered>/recipe_scrapers/_schemaorg.py", line 28, in _contains_schematype
    itemtype = item.get("@type", "")
               ^^^^^^^^
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by jayaddison** [comment]
The problem here seems to be related to an unusual entry in an JSON-LD `@graph` entry on the page.  It contains an item that is the literal value `false` (boolean), instead of a list/object/string value as would usually be expected.  This explains why attempting to call `item.get` fails with the exception described in the stacktrace.
