### ISSUE TITLE
Tine.no scraper issues

### ISSUE THREAD

**Issue by mathiazom** [hhursev/recipe-scrapers#484]
Thanks for filing a bug report with us!

If your request is about a website that is not supported, please open a 'new scraper' issue request instead.

To help get the issue fixed, please fill in the information below.

**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

Some examples:
- https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler
- https://www.tine.no/oppskrifter/middag-og-hovedretter/pizza-og-pai/hvit-pizza-med-gr%C3%B8nnk%C3%A5l

**The version of Python you're using**

Tested on both 3.7.12 and 3.10.2

**The operating system of your environment**

Fedora Linux 35 (Workstation Edition)

**The results you expect to see**

Correct `total_time`, `ingredients` and `instructions`

**The results (including any Python error messages) that you are seeing**

```
>>> from recipe_scrapers import scrape_me
>>> scraper = scrape_me("https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler")
>>> scraper.title()
'Grove havrevafler med gulrot'
>>> scraper.total_time()
0
>>> scraper.yields()
'10'
>>> scraper.ingredients()
[]
>>> scraper.instructions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mathias/.local/lib/python3.10/site-packages/recipe_scrapers/plugins/exception_handling.py", line 63, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/home/mathias/.local/lib/python3.10/site-packages/recipe_scrapers/plugins/html_tags_stripper.py", line 74, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
  File "/home/mathias/.local/lib/python3.10/site-packages/recipe_scrapers/plugins/schemaorg_fill.py", line 46, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/home/mathias/.local/lib/python3.10/site-packages/recipe_scrapers/tineno.py", line 83, in instructions
    ins = instructions.findAll("li", {"class": "o-recipe-steps__step-group"})
AttributeError: 'NoneType' object has no attribute 'findAll'
>>> scraper.image()
'https://www.tine.no/_/recipeimage/w_160%2Ch_90%2Cc_fill%2Cx_2596%2Cy_1460%2Cg_xy_center/recipeimage/fcy10iygtwoiop4dqhxx.jpg'
>>> scraper.host()
'tine.no'
>>> scraper.links()
[{'href': '/oppskrifter', 'class': ['o-kitchen-header__logo']}, {'href': 'https://sso.tine.no/publicuser/forms/login?redir=https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/fisk-og-skalldyr'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/gronnsaker-og-poteter'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/kjott'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/kylling-og-fjarkre'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/pannekaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/pasta-og-ris'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/pizza-og-pai'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/middag-og-hovedretter/supper'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/kaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/kaker/formkaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/kaker/frukt-og-barkaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/kaker/is-og-ostekaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/kaker/krem-og-sjokoladekaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/kaker/vafler-og-smakaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter/forretter-snacks-og-tapas'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter/grot-og-kornblandinger'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter/omeletter-og-pannekaker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter/salater'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter/smorbrod-og-palegg'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/lunsj-og-smaretter/yoghurt'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/bakst'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/bakst/brod-og-rundstykker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/bakst/scones-og-muffins'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/bakst/sot-gjarbakst'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/fromasj-og-mousse'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/frukt-og-bar'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/is-og-sorbet'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/ost'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/puddinger-og-gele'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/supper'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/desserter/sote-snacks-og-godteri'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/sauser-og-dressinger'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/sauser-og-dressinger/kalde-sauser-og-dressinger'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/sauser-og-dressinger/varme-sauser-og-dressinger'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/drikke'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/drikke/kalde-drikker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/drikke/varme-drikker'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/kj%C3%B8tt'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/skalldyr'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/sjokolade'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/fisk'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/frukt-og-b%C3%A6r'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/kylling'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/egg'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/ris'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/yoghurt'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/ost'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/pasta'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/vegetar'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/italiensk-mat'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/asiatisk-mat'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/tradisjonsmat'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/indisk-mat'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/meksikansk-mat'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/halloween'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/jul'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/17.mai-maten'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/h%C3%B8st'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/p%C3%A5ske'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/matpakketips'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/vegetar'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/enkel'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/helg'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/litt-sunnere-middag'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/rask-middag'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/barnevennlig-mat'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/spicy'}, {'class': ['o-kitchen-header--sub-menu__link'], 'href': '/oppskrifter/tema/grill'}, {'href': '/oppskrifter/tema/vafler', 'class': ['m-tags__link']}, {'href': '/oppskrifter/tema/lunsj', 'class': ['m-tags__link']}, {'class': ['o-sentiment--comments'], 'href': '#comments'}, {'href': '/merkevarer/tinemelk/produkter/tinemelk-lettmelk-0-5-fett'}, {'href': '/merkevarer/tine-kefir/produkter/tine-kefir-%C3%B8kologisk'}, {'href': '/merkevarer/tine-sm%C3%B8r/produkter/tine-meierism%C3%B8r'}, {'href': '/merkevarer/tine-brunost/produkter/tine-fl%C3%B8temysost-lett-16-fett'}, {'class': ['o-sharebuttons__social-item'], 'aria-label': 'Del på Facebook', 'href': '//www.facebook.com/sharer.php?u=https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler&title=Grove havrevafler med gulrot ', 'rel': ['nofollow', 'noopener', 'noreferrer'], 'target': '_blank'}, {'class': ['o-sharebuttons__social-item'], 'aria-label': 'Del på Twitter', 'href': '//twitter.com/share?text=Grove havrevafler med gulrot &url=https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler', 'rel': ['nofollow', 'noopener', 'noreferrer'], 'target': '_blank', 'data-reactid': '416'}, {'class': ['o-sharebuttons__social-item'], 'aria-label': 'Del på Pinterest', 'href': '//pinterest.com/pin/create/button/?url=https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler&$description=Grove havrevafler med gulrot ', 'rel': ['nofollow', 'noopener', 'noreferrer'], 'target': '_blank'}, {'class': ['o-sharebuttons__social-item'], 'aria-label': 'Del på epost', 'href': 'mailto:?subject=Grove havrevafler med gulrot &body=https://www.tine.no/oppskrifter/kaker/vafler-og-smakaker/grove-havrevafler', 'rel': ['nofollow', 'noopener', 'noreferrer'], 'target': '_blank'}, {'class': ['m-recipe-card__link'], 'href': '/oppskrifter/middag-og-hovedretter/pizza-og-pai/hvit-pizza-med-gr%C3%B8nnk%C3%A5l'}, {'class': ['m-recipe-card__link'], 'href': '/oppskrifter/lunsj-og-smaretter/grot-og-kornblandinger/yoghurt-naturell-med-brunostm%C3%BCsli'}, {'class': ['m-recipe-card__link'], 'href': '/oppskrifter/middag-og-hovedretter/fisk-og-skalldyr/taco-med-soyaglasert-torsk'}, {'href': '/', 'aria-label': 'tine.no', 'class': ['o-footer__logo-link', 'logo-margin']}, {'href': 'tel:03080'}, {'href': 'tel:004775663080'}, {'href': 'tel:51371606'}, {'href': 'tel:51371606'}, {'href': 'https://twitter.com/tine_sa', 'aria-label': 'twitter'}, {'href': 'https://www.facebook.com/TINEKjokken', 'aria-label': 'facebook'}, {'href': 'https://www.instagram.com/tinekjokken/', 'aria-label': 'instagram'}, {'href': 'https://www.tine.no/kontakt/artikler/ansvarserkl%C3%A6ring-personvern-og-debattregler-p%C3%A5-tines-nettsteder'}, {'href': 'https://www.tine.no/kontakt/artikler/oversikt-over-informasjonskapsler-cookies-p%C3%A5-tine.no'}, {'href': 'https://www.tine.no/kontakt/kontaktskjema'}, {'href': 'https://www.tine.no/kontakt/sporsmal-og-svar'}, {'href': 'https://www.tine.no/kontakt/reklamasjonsskjema'}, {'href': 'https://www.tine.no', 'title': 'TINE.no', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/produkter', 'title': 'Produkter', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/oppskrifter', 'title': 'Oppskrifter', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/om-tine', 'title': 'Om TINE', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/jobb-i-tine', 'title': 'Jobb i TINE', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/v%C3%A5re-nettsider', 'title': 'Våre nettsider', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://medlem.tine.no/forside', 'title': 'Bondens side', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.skolelyst.no/', 'title': 'Skolemelk', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/helse', 'title': 'Helse', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/presserom', 'title': 'Presserom', 'classname': 'o-footer__shortcut-link'}, {'href': 'https://www.tine.no/kontakt', 'title': 'Kontakt', 'classname': 'o-footer__shortcut-link'}]
>>> scraper.nutrients()
{}
```

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [x] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [ ] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by jayaddison** [comment]
Thanks for the detailed bug report @mathiazom!  We'll be ready to help you out with code review when you have a proposed fix for this.
