### ISSUE TITLE
Request for everyplate.com

### ISSUE THREAD

**Issue by stroodle96** [hhursev/recipe-scrapers#535]
We always enjoy adding support for new websites to the library!

To help us out, please check that recipes published on the website you're requesting are public (we can't currently scrape recipes that require an account login) and add sample recipe URL(s) below:

https://www.everyplate.com/recipes/spiced-chickpea-basmati-bowls-624cb1cd6b05a6530a2dcb75?week=2022-W18
https://www.everyplate.com/recipes/lemon-butter-scallops-624cb1a387658a46421eabb2?week=2022-W18

Can you write Python and would you like to help add the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try adding this scraper myself
- [ ] I'd like guidance to help me develop a scraper
- [x] I'd prefer if the `recipe-scrapers` community try to add this

**Comment by stroodle96** [comment]
This was already looked into in issue #512.  Opening separate issue for everyplate.  Thank you!

**Comment by brycied00d** [comment]
I was excited to see EveryPlate support was added!  Unfortunately, EP is still reported as an unsupported site with this latest release.

Steps to reproduce:
1. Created a venv for testing: `python -m venv --system-site-packages --symlinks /tmp/scraper-venv`
2. Install the latest release: `cd /tmp/scraper-venv && ./bin/pip install recipe-scrapers`  Output confirms that 15.6.0 was installed.
3. Simple test output below:

```
$ ./bin/python
Python 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from recipe_scrapers import scrape_me
>>> scraper = scrape_me("https://www.everyplate.com/recipes/sweet-and-saucy-soy-garlic-chicken-67683b92555c15a993e4e003")
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    scraper = scrape_me("https://www.everyplate.com/recipes/sweet-and-saucy-soy-garlic-chicken-67683b92555c15a993e4e003")
  File "/tmp/scraper-venv/lib/python3.13/site-packages/recipe_scrapers/__init__.py", line 1037, in scrape_me
    return scrape_html(html, org_url=url)
  File "/tmp/scraper-venv/lib/python3.13/site-packages/recipe_scrapers/__init__.py", line 1026, in scrape_html
    raise WebsiteNotImplementedError(msg)
recipe_scrapers._exceptions.WebsiteNotImplementedError: recipe-scrapers exception: Website (The website 'everyplate.com' isn't currently supported by recipe-scrapers!
---
If you have time to help us out, please report this as a feature 
request on our bugtracker.) not supported.
>>> 
```

It seems to me that closing this issue was maybe premature.
