### ISSUE TITLE
Unable to parse ingredients and instructions with nested lists

### ISSUE THREAD

**Issue by ozkutuk** [hhursev/recipe-scrapers#545]
Currently the ingredients/instructions of the form `['a', 'b', 'c']` can be parsed properly, whereas `[['a', 'b', 'c']]` or `[['a', 'b'], ['c']]` cannot. This causes issues with [yemek.com](https://yemek.com) recipes:
```python
>>> pg_data = requests.get('https://yemek.com/tarif/tereyagli-pilav/').content
>>> schema = SchemaOrg(pg_data)

>>> schema.data.get('recipeIngredient')
[['2 su bardağı pilavlık pirinç', '3,5 su bardağı sıcak su', '1 yemek kaşığı zeytinyağı', '2 yemek kaşığı tereyağı', '2 yemek kaşığı arpa şehriye', '1,5 çay kaşığı tuz']]

>>> schema.ingredients()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ozkutuk/dev/recipe-test/.venv/lib/python3.9/site-packages/recipe_scrapers/_schemaorg.py", line 150, in ingredients
    return [
  File "/home/ozkutuk/dev/recipe-test/.venv/lib/python3.9/site-packages/recipe_scrapers/_schemaorg.py", line 151, in <listcomp>
    normalize_string(ingredient) for ingredient in ingredients if ingredient
  File "/home/ozkutuk/dev/recipe-test/.venv/lib/python3.9/site-packages/recipe_scrapers/_utils.py", line 127, in normalize_string
    unescaped_string.replace("\xa0", " ")
AttributeError: 'list' object has no attribute 'replace'
```

Ideally [yemek.com](https://yemek.com) would provide these as flat lists. However, it seems that [schema.org validator](https://validator.schema.org/) has no problem parsing this format, so I think it may be a better idea to allow such specifications in our parser as well, rather than specifically patching the [yemek.com](https://yemek.com) scraper.

**Comment by hhursev** [comment]
Fixed with fa61cf2
