### ISSUE TITLE
MicroData not found in wildmode

### ISSUE THREAD

**Issue by vabene1111** [hhursev/recipe-scrapers#561]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

 scrape_me('https://www.deutschesee.de/rezepte/lachsfilet-mit-mediterranem-gemuese.html', wild_mode=True)

**The version of Python you're using**
3.9.5
scrapers version 14.5.0

**The operating system of your environment**
windows/linux
**The results you expect to see**

parsed page

**The results (including any Python error messages) that you are seeing**

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\recipe_scrapers\__init__.py", line 315, in scrape_me
    scraper = SCRAPERS[host_name]
KeyError: 'deutschesee.de'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\recipe_scrapers\__init__.py", line 323, in scrape_me
    raise NoSchemaFoundInWildMode(url_path)
  File "C:\Users\Userz\AppData\Local\Programs\Python\Python39\lib\site-packages\recipe_scrapers\_exceptions.py", line 22, in __init__
    message = f"No Recipe Schema found at {self.url}."
AttributeError: 'NoSchemaFoundInWildMode' object has no attribute 'url'
>>>

```

the page contains proper microdata attributes so i would expect it to find the microdata schema in wild mode but maybe I am missing something (sadly did not have the time to really dive into the code yet, just know microdata used to work, maybe someone knows an easy fix for this)

also btw. since i am not sure if i ever did: thanks everyone a lot for this awesome library!

**Comment by vabene1111** [comment]
ok so the issue appears to be that the wild mode schema parser stops looking for a schema as soon as it finds one of the supported options which is also `WebPage`. I dont know why web page is in the supported schemas but probably because it is a nice fallback if `Recipe `is not. 
I will adjust the parser so that it first looks for `Recipe` and only uses `WebPage` if no recipe is found.
