### ISSUE TITLE
Test integration in VisualStudio Code

### ISSUE THREAD

**Issue by bickerdyke** [hhursev/recipe-scrapers#640]
I'm currently trying to add a new scraper (will add another issue when I have something presentable) but this is my first first towards python, so I may be stupid here :-)

I use Visual Studio Code and would need to start the tests in the debugger. I tried to import the available tests into the VSCode plugin as it should support the unittest Framework, but discovery fails with an error for each test file:

     Failed to import test module: test_zenbelly
     Traceback (most recent call last):
       File "C:\Program 
     Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
       File "C:\Program 
     Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
       File "d:\Marcel\Documents\Projekte\recipe-scrapers\tests\test_zenbelly.py", line 2, in <module>
    from tests import ScraperTest
       File "d:\Marcel\Documents\Projekte\recipe-scrapers\tests\__init__.py", line 5, in <module>
    import responses
     ModuleNotFoundError: No module named 'responses'

Looks like a path/module/include the automated setup missed a path/include/module/whatever. Is anyone using this VSCode feature successfully and knows how to configure?

Maybe we could add that into the documentation for new contributors, to ease their onboarding. ( #617 )

This are my current, automatically generated settings:

```json
{
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        "./tests",
        "-p",
        "test_*.py"
    ],
    "python.testing.pytestEnabled": false,
    "python.testing.unittestEnabled": true
}
```

**Comment by bickerdyke** [comment]
Looks like rebooting helped..... I can run tests with the VSCode testrunner now.
