### ISSUE TITLE
eattolerant.de

### ISSUE THREAD

**Issue by jlssmt** [hhursev/recipe-scrapers#714]
- https://eattolerant.de/hauptgerichte/zucchini-spaghetti-in-leichter-frischkaesesosse-histaminarm-laktosefrei-glutenfrei-fruktosearm/
- https://eattolerant.de/kuchen-muffins-co/histaminarmer-heidelbeer-marmorkuchen-mit-kokos-und-erdmandeln-histaminarm-laktosefrei/

**Comment by jlssmt** [comment]
it's still not working with my PR #719

and i get following error in development environment:
```python
Traceback (most recent call last):
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\main.py", line 10, in <module>
    scraper.title()
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\plugins\exception_handling.py", line 64, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\plugins\html_tags_stripper.py", line 75, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\plugins\normalize_string.py", line 34, in decorated_method_wrapper
    return normalize_string(decorated(self, *args, **kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\plugins\schemaorg_fill.py", line 48, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\eattolerant.py", line 11, in title
    return self.schema.title()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\_schemaorg.py", line 80, in title
    return normalize_string(self.data.get("name"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\PycharmProjects\recipe-scrapers\recipe_scrapers\_utils.py", line 141, in normalize_string
    unescaped_string = html.unescape(string)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\html\__init__.py", line 130, in unescape
    if '&' not in s:
       ^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by jayaddison** [comment]
Hi @jlssmt - it seems that _some_ recipe pages from Eat Tolerant are now accessible/parsable; however it seems to depend upon there existing a `Recipe` schema.org metadata entry on the page.

The first URL you provided doesn't work currently -- but the second one does.  I'm not sure yet whether we should consider this a bug, or simply a limitation of the recipe pages that can be parsed from this site.

So: not perfect, but I thought I'd provide a update to keep you informed.

**Comment by jlssmt** [comment]
@jayaddison cool, thanks for the update.
all new recipes seem to have the working schema.
mealie now also has a OpenAI recipe scraper if your scraper doesn't find anything. i think thats a good combination.
