### ISSUE TITLE
Blueapron parse error

### ISSUE THREAD

**Issue by hsrthe4th** [hhursev/recipe-scrapers#720]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**
- https://www.blueapron.com/recipes/vinaigrette-marinated-chicken-with-pickled-pepper-relish-pasta-salad
- https://www.blueapron.com/recipes/barbecue-chicken-turnovers-with-cone-cabbage-apple-slaw

**The results you expect to see**
Parsed title of the site

**The results (including any Python error messages) that you are seeing**
~~~
Traceback (most recent call last):
  File "/home/user/pthon.py", line 12, in <module>
    scraper.title()
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/plugins/exception_handling.py", line 64, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/plugins/html_tags_stripper.py", line 75, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/plugins/normalize_string.py", line 34, in decorated_method_wrapper
    return normalize_string(decorated(self, *args, **kwargs))
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/plugins/schemaorg_fill.py", line 48, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/blueapron.py", line 11, in title
    return self.schema.title()
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/_schemaorg.py", line 80, in title
    return normalize_string(self.data.get("name"))
  File "/home/user/.local/lib/python3.9/site-packages/recipe_scrapers/_utils.py", line 141, in normalize_string
    unescaped_string = html.unescape(string)
  File "/usr/lib/python3.9/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
~~~

**Script I am running with version 14.28.0**
~~~python
from recipe_scrapers import scrape_me
scraper = scrape_me('https://www.blueapron.com/recipes/barbecue-chicken-turnovers-with-cone-cabbage-apple-slaw')
scraper.title()
~~~

**Comment by jayaddison** [comment]
Thanks for the bug report @hsrthe4th - some clues about what might be happening here:

This [code in the library](https://github.com/hhursev/recipe-scrapers/blob/6b8bf9dc5d6637d0955c04a5f560d00daae5c8e4/recipe_scrapers/_schemaorg.py#L79-L80) isn't checking whether the `name` field exists in the schema.org metadata on the webpage.

```python
return normalize_string(self.data.get("name"))
```

So if `blueapron.com` (or any other website) doesn't contain that schema.org metadata field, then this error could occur.

The quickest fix is probably something along the lines of:

```python
        name = self.data.get("name")
        if name:
            normalize_string(name)
```

...and we should add test coverage for that, too.

**Comment by hsrthe4th** [comment]
It looks like its not just that field, but that blueapron is doing a JS/captcha

Output of pprint(vars(scraper))
```
 {'page_data': b'<html><head><title>blueapron.com</title><style>#cmsg{animati'
              b'on: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{o'
              b'pacity:1;}}</style></head><body style="margin:0"><p id="cmsg'
              b'">Please enable JS and disable any ad blocker</p><script dat'
              b'a-cfasync="false">var dd={\'rt\':\'c\',\'cid\':\'AHrlqAAAAAMAw9'
              b"M35iRSFgoALRqYiQ==','hsh':'F3AD613367B7A9A05F49CB61F3AC0B','"
              b"t':'bv','s':37086,'e':'9b7b4b331ef96c805a28a930d4baea266b206"
              b"1cab369adea9eb7ae6b8043ab67','host':'geo.captcha-delivery.co"
              b'm\'}</script><script data-cfasync="false" src="https://ct.cap'
              b'tcha-delivery.com/c.js"></script></body></html>\n',
 'schema': <recipe_scrapers._schemaorg.SchemaOrg object at 0x7f48ecdedfa0>,
 'soup': <html><head><title>blueapron.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0">
 <p id="cmsg">Please enable JS and disable any ad blocker</p>
 <script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAw9M35iRSFgoALRqYiQ==','hsh':'F3AD613367B7A9A05F49CB61F3AC0B','t':'bv','s':37086,'e':'9b7b4b331ef96c805a28a930d4baea266b2061cab369adea9eb7ae6b8043ab67','host':'geo.captcha-delivery.com'}</script>
 <script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>
,
 'url': 'https://www.blueapron.com/recipes/barbecue-chicken-turnovers-with-cone-cabbage-apple-slaw',
 'wild_mode': False}
```

**Comment by mananomartinez** [comment]
Can confirm that I run into the same problem with BA and captcha.

**Comment by hhursev** [comment]
closing as this package is not meant to be used in places where bypassing of bot protection is needed
