### ISSUE TITLE
hellofresh.de returns bug

### ISSUE THREAD

**Issue by sHooPmyWooP** [hhursev/recipe-scrapers#747]
**Pre-filing checks**

- [X] I have searched for open issues that report the same problem
- [X] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.hellofresh.de/recipes/conchiglie-bruschetta-art-mit-bunten-kirschtomaten-63d8eefc99d8bdb7e60b5efb

**The results you expect to see**

...

**The results (including any Python error messages) that you are seeing**
```python
scraper = scrape_me("above url")
sraper.title() 
```
raises this error
```
s.title()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\plugins\exception_handling.py", line 64, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\plugins\html_tags_stripper.py", line 75, in decorated_method_wrapper
    decorated_func_result = decorated(self, *args, **kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\plugins\normalize_string.py", line 34, in decorated_method_wrapper
    return normalize_string(decorated(self, *args, **kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\plugins\schemaorg_fill.py", line 48, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\hellofresh.py", line 11, in title
    return self.schema.title()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\_schemaorg.py", line 80, in title
    return normalize_string(self.data.get("name"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\recipe_scrapers\_utils.py", line 141, in normalize_string
    unescaped_string = html.unescape(string)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\html\__init__.py", line 130, in unescape
    if '&' not in s:
       ^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jayaddison** [comment]
The title of the recipe that appears in `schema.org` is fairly verbose for this recipe.. but it does work and emits the same metadata as found in the HTML source when I try it; so I'm going to close this as resolved.

```python
>> s.title()
'Conchiglie Bruschetta Art mit bunten Kirschtomaten Bei diesem Gericht wird 50% weniger CO2e durch Zutaten verursacht als bei einem durchschnittlichen HelloFresh Rezept'
```

Please let us know if this problem still occurs, and/or file a separate bugreport for any other problems you find.  Thank you for letting us know about it!
