### ISSUE TITLE
Real Simple Yields

### ISSUE THREAD

**Issue by jbelluch** [hhursev/recipe-scrapers#837]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- [https://www.realsimple.com/crispy-peanut-tofu-with-sugar-snap-peas-and-peppers-recipe-7229744]

...

**The results you expect to see**
Expecting the yield to be displayed when I call recipe.yields()
...

**The results (including any Python error messages) that you are seeing**
recipe.yields()
Traceback (most recent call last):
  File "<pyshell#67>", line 1, in <module>
    recipe.yields()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/exception_handling.py", line 64, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/schemaorg_fill.py", line 48, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/realsimple.py", line 24, in yields
    self.soup.find("div", string=re.compile(r"Yield:")).parent.get_text()
AttributeError: 'NoneType' object has no attribute 'parent'
...

*Fix*
I fixed this locally with the following change to realsimple.py:

def yields(self):
        return get_yields(
            self.schema.yields()
        )

**Comment by jayaddison** [comment]
A fix for this (and #838) is available in now available in version 14.45.0 of the library on PyPi.
