### ISSUE TITLE
Food & Wine Yield Error

### ISSUE THREAD

**Issue by jbelluch** [hhursev/recipe-scrapers#879]
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://https://www.foodandwine.com/recipes/candied-sweet-potatoes-bourbon

...

**The results you expect to see**
Expect to get a yield amount of 8. I get error. It appears the yield is not in the default schema. Need to adjust to look in HTML code I believe.

...

**The results (including any Python error messages) that you are seeing**
Getting error when referencing the .yields() property:
"recipe.yields()
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    recipe.yields()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/exception_handling.py", line 64, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/plugins/schemaorg_fill.py", line 48, in decorated_method_wrapper
    return decorated(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/foodandwine.py", line 17, in yields
    return self.schema.yields()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/recipe_scrapers/_schemaorg.py", line 134, in yields
    raise SchemaOrgException("Servings information not found in SchemaOrg")
recipe_scrapers._exceptions.SchemaOrgException: recipe-scrapers exception: Servings information not found in SchemaOrg"
...

**Comment by jayaddison** [comment]
A fixup for this is now available in version 14.49.4, as found on PyPi.
